### PR TITLE
Update surrogate key to single arg

### PR DESCRIPTION
**Pull request by kingfink**
Dismisses the deprecation warning

### CODE REVIEW

**Comment by clrcrl** [comment]
Nice! The list syntax was introduced in utils v0.4.0 — can you update the [packages.yml](https://github.com/fishtown-analytics/dbt-event-logging/blob/master/packages.yml) to have a lower bound like so:
```
packages:
 - package: fishtown-analytics/dbt_utils
   version: [">=0.4.0", "<0.6.0"]
```
(I've also increased the upper bound as there was a new release for dbt-utils :) )

**Comment by kingfink** [comment]
Done!

**Comment by clrcrl** [comment]
Perf! let me kick off the tests :)

**Comment by clrcrl** [comment]
Ah, the tests are failing for an unrelated reason. Checkout #33

**Comment by clrcrl** [comment]
Can you pull the latest changes from master into this branch? And then I'll re-kick off the tests. Sorry about this!

**Comment by kingfink** [comment]
No problem! I _think_ I've pulled in the changes. Let me know if that works!

**Pull request merged**
