### PR TITLE
Add option to customise audit database

### PR DESCRIPTION
**Pull request by danieldiamond**
## Description & motivation
Add `Customising audit database` macro

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)

### CODE REVIEW

**Comment by danieldiamond** [comment]
@joellabes is this something you're able to review?

**Comment by jasnonaz** [comment]
Hi @danieldiamond - thank you for the contribution! Joel is out on leave for the time being but @dbeatty10 might be able to take a look for us.

**Comment by danieldiamond** [comment]
thanks team, @dbeatty10 any chance i can help expedite this review?

**Comment by danieldiamond** [comment]
@jasnonaz is there anyone else that can review this?

**Review by dbeatty10 — APPROVED** [review]
Hi @danieldiamond, this looks straight-forward and makes sense for filling in a missing gap -- thank you for this useful contribution! ✨ 

After merging this, I'm going to do the following prior to the next release:
- lowercase all references to "DBT" as "dbt" (other than those sentences that are currently in all caps)
- add references and links to the analogous [generate_schema_name](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas#how-does-dbt-generate-a-models-schema-name) and [generate_database_name](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-databases#generate_database_name) macros

**Pull request merged**
